version: '3'

services:
  biliboba:
    image: registry.csc.sibsutis.ru/is141s14/v-tech-labs:latest
    container_name: biliboba
    networks:
      - app-network
    expose:
      - "3000"

  bilibiba:
    image: containous/whoami
    container_name: bilibiba
    networks:
      - app-network
    expose:
      - "80"

  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - app-network
    depends_on:
      - biliboba
      - bilibiba

networks:
  app-network:
    driver: bridge